apiVersion: apps/v1
kind: Deployment
metadata:
     name: maven-deployment
     labels:
        app: maven-app
spec:
  replicas: 1
  selector:
      matchLabels:
          app: maven-app
  template:
    metadata:
         labels:
            app: maven-app
    spec:
      containers:
          - name: myconts
            image: warapp
            imagePullPolicy: Never
            ports:
              - containerPort: 8080
