apiVersion: v1
kind: Service
metadata:
    name: maven-service
spec:
  type: nodePort
  selector:
     app: maven-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30017
